[project]
name = "cuscuz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "jinja2>=3.1.6",
]

[dependency-groups]
dev = [
    "ruff>=0.13.3",
]
