from .element import Element
from typing import TYPE_CHECKING

tags = [
    "div",
    "span",
    "p",
    "a",
    "img",
    "br",
    "hr",
    "input",
    "meta",
    "link",
    "ul",
    "ol",
    "li",
    "table",
    "tr",
    "td",
    "th",
    "thead",
    "tbody",
    "footer",
    "header",
    "section",
    "article",
    "nav",
    "form",
    "button",
    "html",
    "head",
    "title",
    "body",
    "h1",
    "main",
]


def create_tag(tag: str, **attributes) -> Element:
    # Converte 'class_name' para 'class' no HTML
    if "class_name" in attributes:
        attributes["class"] = attributes.pop("class_name")
    element = Element(tag, attributes)
    if "children" in attributes:
        children: list[Element] | Element | str = attributes.pop("children")
        if isinstance(children, list):
            for child in children:
                element.add_child(child)
        else:
            element.add_child(children)
    return element


def __getattr__(name: str):
    if name in tags:
        return lambda **attributes: create_tag(name, **attributes)
    raise AttributeError(f"module has no attribute '{name}'")


# Para type checking
if TYPE_CHECKING:

    def div(**attributes) -> Element: ...
    def span(**attributes) -> Element: ...
    def p(**attributes) -> Element: ...
    def a(**attributes) -> Element: ...
    def img(**attributes) -> Element: ...
    def br(**attributes) -> Element: ...
    def hr(**attributes) -> Element: ...
    def input(**attributes) -> Element: ...
    def meta(**attributes) -> Element: ...
    def link(**attributes) -> Element: ...
    def ul(**attributes) -> Element: ...
    def ol(**attributes) -> Element: ...
    def li(**attributes) -> Element: ...
    def table(**attributes) -> Element: ...
    def tr(**attributes) -> Element: ...
    def td(**attributes) -> Element: ...
    def th(**attributes) -> Element: ...
    def thead(**attributes) -> Element: ...
    def tbody(**attributes) -> Element: ...
    def footer(**attributes) -> Element: ...
    def header(**attributes) -> Element: ...
    def section(**attributes) -> Element: ...
    def article(**attributes) -> Element: ...
    def nav(**attributes) -> Element: ...
    def form(**attributes) -> Element: ...
    def button(**attributes) -> Element: ...
    def html(**attributes) -> Element: ...
    def head(**attributes) -> Element: ...
    def title(**attributes) -> Element: ...
    def body(**attributes) -> Element: ...
    def h1(**attributes) -> Element: ...
    def main(**attributes) -> Element: ...
